# Generated by Django 2.2.7 on 2019-11-06 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xsd_trips', '0005_tripmember_state_20170220_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_owner', to='xsd_members.MemberProfile', verbose_name='Organiser'),
        ),
    ]
