# Generated by Django 2.2.7 on 2019-11-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsd_kit', '0002_auto_20141109_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='club_owned',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='needs_testing',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='kit',
            name='type',
            field=models.CharField(choices=[('WETS', 'Wetsuit'), ('SEMI', 'Semidry'), ('DRYS', 'Drysuit'), ('BCD', 'BCD'), ('WING', 'Wing'), ('REGS', 'Regs'), ('CYL', 'Cylinder'), ('MASK', 'Mask'), ('FINS', 'Fins'), ('SNRK', 'Snorkel'), ('COMP', 'Computer'), ('TORH', 'Torch'), ('SMB', 'SMB'), ('DSMB', 'DSMB'), ('REEL', 'Reel')], max_length=64),
        ),
        migrations.AlterField(
            model_name='loan',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
