# Generated by Django 2.2.7 on 2019-11-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsd_members', '0016_auto_20170506_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='bsac_direct_member',
            field=models.BooleanField(default=False, help_text='Adjusts the wording presented to the member when BSAC expires.', verbose_name='BSAC Direct Member'),
        ),
    ]
