# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-12 20:43


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xsd_training', '0011_auto_20170507_0207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performedlesson',
            options={'get_latest_by': 'date', 'ordering': ['trainee__last_name', 'date']},
        ),
    ]
