# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-29 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xsd_training', '0012_auto_20190112_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
