# Generated by Django 2.2.7 on 2019-11-06 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xsd_training', '0013_qualification_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='mode',
            field=models.CharField(choices=[('TH', 'Theory'), ('SW', 'Sheltered Water'), ('OW', 'Open Water'), ('DP', 'Dry Practical'), ('XP', 'Experience'), ('WS', 'Workshop'), ('PQ', 'Post Qualification'), ('XO', 'Cross-over'), ('AS', 'Assessment')], max_length=2),
        ),
        migrations.AlterField(
            model_name='performedlesson',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_instructor_cached': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pl_instructor', to='xsd_members.MemberProfile'),
        ),
        migrations.AlterField(
            model_name='performedlesson',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='xsd_training.Lesson'),
        ),
        migrations.AlterField(
            model_name='sdc',
            name='category',
            field=models.CharField(choices=[('clu', 'Club Diving'), ('saf', 'Safety and Rescue'), ('sea', 'Seamanship'), ('spe', 'Special Interest'), ('tec', 'Technical')], max_length=3),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, help_text='Optional name for session', max_length=64),
        ),
        migrations.AlterField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, help_text='Viewable by instructors and trainees in session.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='when',
            field=models.DateTimeField(help_text='Formatted like: DD/MM/YYYY HH:MM'),
        ),
        migrations.AlterField(
            model_name='session',
            name='where',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='xsd_sites.Site'),
        ),
    ]
